# Generated by Django 5.2.6 on 2025-10-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='annual_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='course',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_relation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='student_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='employee_student_id',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Employee ID/Student Roll No'),
            preserve_default=False,
        ),
    ]
