# Generated by Django 5.2.7 on 2025-10-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_initial'),
        ('patients', '0005_patient_unique_user_patient_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='medicines_prescribed',
            field=models.TextField(blank=True, help_text='Free text for medicine names'),
        ),
        migrations.CreateModel(
            name='TreatmentMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity prescribed')),
                ('dosage', models.CharField(help_text="e.g., '1 tablet twice daily'", max_length=200)),
                ('duration_days', models.IntegerField(default=7, help_text='Treatment duration in days')),
                ('stock_deducted', models.BooleanField(default=False, help_text='Whether stock was reduced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medicines.medicine')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicines', to='patients.treatment')),
            ],
            options={
                'db_table': 'treatment_medicines',
                'unique_together': {('treatment', 'medicine')},
            },
        ),
    ]
