# Generated by Django 5.2.7 on 2026-01-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_treatment_medicines_prescribed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='unique_user_patient_record',
        ),
    ]
