"""
Export utilities for generating Excel files
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from django.http import HttpResponse
from datetime import datetime


def create_excel_response(filename):
    """Create HTTP response for Excel file download"""
    response = HttpResponse(
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response


def style_header_row(worksheet, row_num=1):
    """Apply styling to header row"""
    header_fill = PatternFill(start_color='366092', end_color='366092', fill_type='solid')
    header_font = Font(bold=True, color='FFFFFF', size=11)
    
    for cell in worksheet[row_num]:
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')


def auto_adjust_column_width(worksheet):
    """Auto-adjust column widths based on content"""
    for column in worksheet.columns:
        max_length = 0
        column_letter = get_column_letter(column[0].column)
        
        for cell in column:
            try:
                if cell.value:
                    max_length = max(max_length, len(str(cell.value)))
            except:
                pass
        
        adjusted_width = min(max_length + 2, 50)  # Cap at 50 characters
        worksheet.column_dimensions[column_letter].width = adjusted_width


def add_border_to_cells(worksheet, start_row=1, end_row=None):
    """Add borders to all cells"""
    thin_border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    if end_row is None:
        end_row = worksheet.max_row
    
    for row in worksheet.iter_rows(min_row=start_row, max_row=end_row):
        for cell in row:
            cell.border = thin_border


def create_workbook_with_metadata(title, generated_by):
    """Create a new workbook with metadata"""
    wb = Workbook()
    ws = wb.active
    
    # Add metadata sheet
    metadata_sheet = wb.create_sheet('Info', 0)
    metadata_sheet['A1'] = 'Report Information'
    metadata_sheet['A1'].font = Font(bold=True, size=14)
    
    metadata_sheet['A3'] = 'Report Title:'
    metadata_sheet['B3'] = title
    metadata_sheet['A4'] = 'Generated By:'
    metadata_sheet['B4'] = generated_by
    metadata_sheet['A5'] = 'Generated At:'
    metadata_sheet['B5'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    metadata_sheet['A6'] = 'System:'
    metadata_sheet['B6'] = 'KLH Medcare - KLH Medcare Records Database'
    
    # Style metadata
    for row in metadata_sheet['A3:A6']:
        for cell in row:
            cell.font = Font(bold=True)
    
    metadata_sheet.column_dimensions['A'].width = 20
    metadata_sheet.column_dimensions['B'].width = 40
    
    return wb


def export_queryset_to_excel(queryset, columns, filename, title, generated_by):
    """
    Generic function to export any queryset to Excel
    
    Args:
        queryset: Django queryset to export
        columns: List of tuples (field_name, header_name, value_function)
                 value_function is optional, can be a callable that takes obj
        filename: Name of the file to download
        title: Report title
        generated_by: Username of person generating report
    """
    wb = create_workbook_with_metadata(title, generated_by)
    ws = wb.create_sheet('Data', 1)
    wb.active = ws
    
    # Write headers
    headers = [col[1] for col in columns]
    ws.append(headers)
    style_header_row(ws)
    
    # Write data
    for obj in queryset:
        row_data = []
        for col in columns:
            field_name = col[0]
            value_func = col[2] if len(col) > 2 else None
            
            if value_func and callable(value_func):
                value = value_func(obj)
            elif hasattr(obj, field_name):
                value = getattr(obj, field_name)
            elif isinstance(obj, dict):
                value = obj.get(field_name, '')
            else:
                value = ''
            
            # Format value
            if value is None:
                value = ''
            elif isinstance(value, datetime):
                value = value.strftime('%Y-%m-%d %H:%M:%S')
            elif isinstance(value, bool):
                value = 'Yes' if value else 'No'
            
            row_data.append(value)
        
        ws.append(row_data)
    
    # Apply styling
    add_border_to_cells(ws)
    auto_adjust_column_width(ws)
    
    # Create response
    response = create_excel_response(filename)
    wb.save(response)
    return response
