# Generated by Django 5.2.6 on 2025-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10, unique=True)),
                ('bed_type', models.CharField(choices=[('general', 'General Bed'), ('icu', 'ICU Bed'), ('isolation', 'Isolation Bed'), ('observation', 'Observation Bed')], default='general', max_length=20)),
                ('ward', models.CharField(default='General Ward', max_length=50)),
                ('floor', models.CharField(default='Ground', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Being Cleaned')], default='available', max_length=20)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('has_oxygen', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beds',
                'ordering': ['bed_number'],
            },
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=20)),
                ('admission_date', models.DateTimeField()),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('actual_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('condition', models.TextField()),
                ('special_requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bed_allocations',
                'ordering': ['-admission_date'],
            },
        ),
    ]
