# Generated by Django 6.0.1 on 2026-01-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes about this bed')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('has_oxygen', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beds',
                'ordering': ['bed_number'],
            },
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(help_text='Employee/Student ID', max_length=20)),
                ('admission_date', models.DateTimeField()),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('actual_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('condition', models.TextField()),
                ('special_requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bed_allocations',
                'ordering': ['-admission_date'],
            },
        ),
    ]
