# Generated by Django 5.2.10 on 2026-01-14 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bedallocation',
            name='allocated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_allocations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedallocation',
            name='attending_doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='bed_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedallocation',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='bedallocation',
            name='patient_record',
            field=models.ForeignKey(blank=True, help_text='Linked patient record for data consistency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_allocations', to='patients.patient'),
        ),
    ]
