# Generated by Django 5.2.6 on 2025-10-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bed_type',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='last_cleaned',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='maintenance_date',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='ward',
        ),
        migrations.AddField(
            model_name='bed',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes about this bed'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20),
        ),
    ]
