# Generated by Django 5.2.7 on 2025-10-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0003_remove_bed_bed_type_remove_bed_floor_and_more'),
        ('patients', '0006_alter_treatment_medicines_prescribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedallocation',
            name='patient_record',
            field=models.ForeignKey(blank=True, help_text='Linked patient record for data consistency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_allocations', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='bedallocation',
            name='patient_id',
            field=models.CharField(help_text='Employee/Student ID', max_length=20),
        ),
    ]
