# Generated by Django 5.2.7 on 2025-11-06 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0004_add_patient_record_fk'),
        ('patients', '0006_alter_treatment_medicines_prescribed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bedallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('bed',), name='unique_active_bed_allocation', violation_error_message='This bed already has an active allocation. Please discharge the current patient first.'),
        ),
    ]
