# Generated by Django 5.2.7 on 2026-01-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_bedallocation_unique_active_bed_allocation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bedallocation',
            name='unique_active_bed_allocation',
        ),
    ]
