# Generated by Django 6.0.1 on 2026-01-14 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaner_name', models.CharField(default='Unknown Cleaner', help_text='Name of the person who performed the cleaning', max_length=100)),
                ('cleaner_contact', models.CharField(blank=True, help_text='Contact number if available', max_length=15)),
                ('cleaning_date', models.DateField(default=datetime.date.today, help_text='The date when the cleaning was performed')),
                ('start_time', models.TimeField(blank=True, help_text='Time when cleaning started', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Time when cleaning finished', null=True)),
                ('supplies_used', models.TextField(blank=True, help_text='Cleaning supplies used (detergent, disinfectant, etc.)')),
                ('areas_cleaned', models.TextField(default='Medical room general cleaning', help_text='List the specific areas that were cleaned (beds, floors, bathrooms, etc.)')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or observations')),
                ('quality_rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Quality rating from 1-5 stars (optional)', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Room Cleaning Record',
                'verbose_name_plural': 'Medical Room Cleaning Records',
                'db_table': 'cleaning_records',
                'ordering': ['-cleaning_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CleaningStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this cleaning staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cleaning Staff',
                'verbose_name_plural': 'Cleaning Staff',
                'db_table': 'cleaning_staff',
                'ordering': ['name'],
            },
        ),
    ]
