# Generated by Django 6.0.1 on 2026-01-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrecord',
            name='recorded_by',
            field=models.ForeignKey(help_text='Doctor or nurse who recorded this cleaning', limit_choices_to={'user_type__in': ['doctor', 'nurse']}, on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_records_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
