# Generated by Django 5.2.10 on 2026-01-14 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Doctor or nurse who recorded this cleaning', limit_choices_to={'user_type__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_records_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
