# Generated by Django 5.2.7 on 2025-11-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_approved_at_user_approved_by_user_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('principal', 'Principal'), ('hod', 'Head of Department'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist/Stock Manager'), ('employee', 'Employee'), ('student', 'Student')], default='student', max_length=15),
        ),
    ]
