# Generated by Django 5.2.7 on 2026-01-12 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_first_name', models.CharField(max_length=150)),
                ('current_last_name', models.CharField(max_length=150)),
                ('current_username', models.CharField(max_length=150)),
                ('requested_first_name', models.CharField(blank=True, max_length=150)),
                ('requested_last_name', models.CharField(blank=True, max_length=150)),
                ('requested_username', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField(help_text='Reason for requesting the change')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's notes or reason for rejection")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting the change', on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Change Request',
                'verbose_name_plural': 'Profile Change Requests',
                'db_table': 'profile_change_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='pcr_user_status_idx'), models.Index(fields=['status', 'created_at'], name='pcr_status_created_idx')],
            },
        ),
    ]
