# Generated by Django 6.0.1 on 2026-01-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetransaction',
            name='patient_record',
            field=models.ForeignKey(blank=True, help_text='Linked patient for issued medicines', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_transactions', to='patients.patient'),
        ),
    ]
