# Generated by Django 5.2.7 on 2025-10-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_initial'),
    ]

    operations = [
    ]
