# Generated by Django 5.2.7 on 2025-10-26 08:14

from django.db import migrations
from django.db.models import Sum
from django.utils import timezone


def create_received_transactions_for_existing_stock(apps, schema_editor):
    """
    Create RECEIVED transactions for all medicines with current stock > 0
    that don't have matching RECEIVED transactions.
    
    This fixes the issue where medicines were created with initial stock
    but no corresponding transaction record.
    """
    Medicine = apps.get_model('medicines', 'Medicine')
    MedicineTransaction = apps.get_model('medicines', 'MedicineTransaction')
    User = apps.get_model('users', 'User')
    
    # Get a system user (first admin/pharmacist) to attribute transactions to
    system_user = User.objects.filter(user_type__in=['admin', 'pharmacist']).first()
    
    if not system_user:
        # If no admin/pharmacist exists, use any user
        system_user = User.objects.first()
    
    if not system_user:
        print("⚠️  No users found. Cannot create transactions.")
        return
    
    fixed_count = 0
    
    for medicine in Medicine.objects.all():
        # Calculate what stock SHOULD be based on transactions
        received = MedicineTransaction.objects.filter(
            medicine=medicine, 
            transaction_type='received'
        ).aggregate(total=Sum('quantity'))['total'] or 0
        
        issued = MedicineTransaction.objects.filter(
            medicine=medicine, 
            transaction_type='issued'
        ).aggregate(total=Sum('quantity'))['total'] or 0
        
        expired = MedicineTransaction.objects.filter(
            medicine=medicine, 
            transaction_type='expired'
        ).aggregate(total=Sum('quantity'))['total'] or 0
        
        adjustment = MedicineTransaction.objects.filter(
            medicine=medicine, 
            transaction_type='adjustment'
        ).aggregate(total=Sum('quantity'))['total'] or 0
        
        expected_stock = received - issued - expired - adjustment
        actual_stock = medicine.current_stock
        
        # If there's a discrepancy, create a RECEIVED transaction to fix it
        if actual_stock != expected_stock:
            difference = actual_stock - expected_stock
            
            if difference > 0:
                # Need to add RECEIVED transaction
                MedicineTransaction.objects.create(
                    medicine=medicine,
                    transaction_type='received',
                    quantity=difference,
                    date=medicine.created_at or timezone.now(),
                    reference_number='MIGRATION-FIX',
                    supplier='Initial Stock / Data Migration',
                    performed_by=system_user,
                    remarks=f'Auto-generated: Reconciliation of existing stock. '
                            f'Expected: {expected_stock}, Actual: {actual_stock}, Added: {difference}'
                )
                fixed_count += 1
                print(f'✅ {medicine.name}: Added RECEIVED transaction for {difference} units')
            elif difference < 0:
                # Stock is less than transactions indicate - create adjustment
                MedicineTransaction.objects.create(
                    medicine=medicine,
                    transaction_type='adjustment',
                    quantity=abs(difference),
                    date=timezone.now(),
                    performed_by=system_user,
                    remarks=f'Auto-generated: Stock adjustment. '
                            f'Expected: {expected_stock}, Actual: {actual_stock}, Removed: {abs(difference)}'
                )
                fixed_count += 1
                print(f'✅ {medicine.name}: Added ADJUSTMENT transaction for {abs(difference)} units')
    
    print(f'\n✅ Migration complete: Fixed {fixed_count} medicines')


def reverse_migration(apps, schema_editor):
    """
    Remove auto-generated transactions if migration is reversed.
    """
    MedicineTransaction = apps.get_model('medicines', 'MedicineTransaction')
    
    # Delete transactions created by this migration
    deleted = MedicineTransaction.objects.filter(
        reference_number='MIGRATION-FIX'
    ).delete()
    
    print(f'Removed {deleted[0]} auto-generated transactions')


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_add_initial_stock_transactions'),
        ('users', '0002_user_approved_at_user_approved_by_user_course_and_more'),  # Need users for performed_by
    ]

    operations = [
        migrations.RunPython(
            create_received_transactions_for_existing_stock,
            reverse_migration
        ),
    ]
