# Generated by Django 5.2.7 on 2026-01-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_add_received_transactions_for_existing_stock'),
        ('patients', '0007_remove_patient_unique_user_patient_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetransaction',
            name='patient_record',
            field=models.ForeignKey(blank=True, help_text='Linked patient for issued medicines', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_transactions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='medicinetransaction',
            name='patient',
            field=models.CharField(blank=True, help_text='Patient name for display (auto-populated from patient_record or manual for old records)', max_length=200),
        ),
    ]
