# Generated by Django 5.2.7 on 2026-01-13 07:13

from django.db import migrations


def link_patient_records(apps, schema_editor):
    """Link existing MedicineTransaction records to Patient records by name"""
    MedicineTransaction = apps.get_model('medicines', 'MedicineTransaction')
    Patient = apps.get_model('patients', 'Patient')
    
    transactions_with_patient_name = MedicineTransaction.objects.exclude(patient='').exclude(patient__isnull=True)
    
    linked_count = 0
    unlinked_count = 0
    
    for transaction in transactions_with_patient_name:
        # Try to find matching patient by name
        patient = Patient.objects.filter(name=transaction.patient).first()
        
        if patient:
            transaction.patient_record = patient
            transaction.save(update_fields=['patient_record'])
            linked_count += 1
        else:
            unlinked_count += 1
    
    print(f"Data migration complete: {linked_count} transactions linked, {unlinked_count} could not be linked (patient not found)")


def reverse_link(apps, schema_editor):
    """Reverse operation - clear patient_record links"""
    MedicineTransaction = apps.get_model('medicines', 'MedicineTransaction')
    MedicineTransaction.objects.all().update(patient_record=None)


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_add_patient_record_fk'),
        ('patients', '0007_remove_patient_unique_user_patient_record'),
    ]

    operations = [
        migrations.RunPython(link_patient_records, reverse_link),
    ]
